"""add companies, skills, candidate_skills, async_jobs, audit_log

Revision ID: 48b43c88a821
Revises: 21245b272011
Create Date: 2026-07-29 06:18:17.346329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '48b43c88a821'
down_revision: Union[str, None] = '21245b272011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('async_jobs',
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='async_job_status'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_async_jobs_job_type'), 'async_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_async_jobs_status'), 'async_jobs', ['status'], unique=False)
    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Enum('SIZE_1_10', 'SIZE_11_50', 'SIZE_51_200', 'SIZE_201_1000', 'SIZE_1000_PLUS', name='company_size'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_table('skills',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('LANGUAGE', 'FRAMEWORK', 'DATABASE', 'DEVOPS', 'CLOUD', 'TOOL', 'SOFT_SKILL', 'OTHER', name='skill_category'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_log',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('candidate_skills',
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency', sa.Enum('NOVICE', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiency_level'), nullable=False),
    sa.Column('evidence_weight', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_profile_id', 'skill_id')
    )
    op.create_index(op.f('ix_candidate_skills_candidate_profile_id'), 'candidate_skills', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_candidate_skills_skill_id'), 'candidate_skills', ['skill_id'], unique=False)
    op.add_column('recruiter_profiles', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_recruiter_profiles_company_id'), 'recruiter_profiles', ['company_id'], unique=False)
    op.create_foreign_key(
        'fk_recruiter_profiles_company_id_companies',
        'recruiter_profiles', 'companies', ['company_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_recruiter_profiles_company_id_companies', 'recruiter_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_recruiter_profiles_company_id'), table_name='recruiter_profiles')
    op.drop_column('recruiter_profiles', 'company_id')
    op.drop_index(op.f('ix_candidate_skills_skill_id'), table_name='candidate_skills')
    op.drop_index(op.f('ix_candidate_skills_candidate_profile_id'), table_name='candidate_skills')
    op.drop_table('candidate_skills')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('skills')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_async_jobs_status'), table_name='async_jobs')
    op.drop_index(op.f('ix_async_jobs_job_type'), table_name='async_jobs')
    op.drop_table('async_jobs')
    # ### end Alembic commands ###
    # Native Postgres enum types survive `drop_table` (a table's column is not
    # the type's only possible owner) and must be dropped explicitly, in
    # reverse dependency order.
    bind = op.get_bind()
    sa.Enum(name='proficiency_level').drop(bind, checkfirst=True)
    sa.Enum(name='skill_category').drop(bind, checkfirst=True)
    sa.Enum(name='company_size').drop(bind, checkfirst=True)
    sa.Enum(name='async_job_status').drop(bind, checkfirst=True)
