"""add student profile builder columns and tables

Adds section 1 fields plus the derived `profile_strength`/`is_discoverable`
to `candidate_profiles`, and the five claim tables backing sections 2-5.

Hand-written rather than autogenerated for one reason worth keeping: the
`verification_status` enum is shared by four tables. Alembic's autogenerate
emits an inline `sa.Enum(...)` per `create_table`, and Postgres raises
`DuplicateObject` on the second `CREATE TYPE`. The type is therefore created
once up front, and every column below references it with `create_type=False`.

Revision ID: c3f1a9d47b02
Revises: 48b43c88a821
Create Date: 2026-07-31 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c3f1a9d47b02'
down_revision: Union[str, None] = '48b43c88a821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Every type is declared with `create_type=False` and created explicitly in
# `upgrade()`. Without it, SQLAlchemy emits an implicit CREATE TYPE the first
# time a type is used in `create_table`/`add_column` — which duplicates the
# explicit create for every enum, and additionally collides with itself for
# `verification_status`, whose four tables would each try to create it.
verification_status = postgresql.ENUM(
    'UNVERIFIED', 'PENDING', 'VERIFIED', 'REJECTED',
    name='verification_status',
    create_type=False,
)
degree_type = postgresql.ENUM(
    'BTECH', 'BE', 'BSC', 'BCA', 'MTECH', 'MSC', 'MCA', 'MBA', 'PHD', 'OTHER',
    name='degree_type',
    create_type=False,
)
branch_enum = postgresql.ENUM(
    'CSE', 'IT', 'ECE', 'EEE', 'MECHANICAL', 'CIVIL', 'CHEMICAL', 'AIML', 'DATA_SCIENCE', 'OTHER',
    name='branch',
    create_type=False,
)
target_role = postgresql.ENUM(
    'BACKEND', 'FRONTEND', 'FULLSTACK', 'MOBILE', 'DATA_ENGINEER', 'DATA_SCIENTIST',
    'ML_ENGINEER', 'DEVOPS', 'QA', 'SECURITY', 'OTHER',
    name='target_role',
    create_type=False,
)
coding_platform = postgresql.ENUM(
    'LEETCODE', 'CODEFORCES', 'HACKERRANK', name='coding_platform', create_type=False
)
project_kind = postgresql.ENUM('REPOSITORY', 'DESCRIBED', name='project_kind', create_type=False)
employment_type = postgresql.ENUM(
    'INTERNSHIP', 'FREELANCE', 'PART_TIME', name='employment_type', create_type=False
)


def upgrade() -> None:
    bind = op.get_bind()

    verification_status.create(bind, checkfirst=True)
    degree_type.create(bind, checkfirst=True)
    branch_enum.create(bind, checkfirst=True)
    target_role.create(bind, checkfirst=True)
    coding_platform.create(bind, checkfirst=True)
    project_kind.create(bind, checkfirst=True)
    employment_type.create(bind, checkfirst=True)

    # --- Section 1 + derived discoverability state on candidate_profiles ---
    op.add_column('candidate_profiles', sa.Column('headline', sa.String(length=200), nullable=True))
    op.add_column('candidate_profiles', sa.Column('college', sa.String(length=200), nullable=True))
    op.add_column(
        'candidate_profiles',
        sa.Column('degree', degree_type, nullable=True),
    )
    op.add_column(
        'candidate_profiles',
        sa.Column('branch', branch_enum, nullable=True),
    )
    op.add_column('candidate_profiles', sa.Column('graduation_year', sa.Integer(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('location', sa.String(length=120), nullable=True))
    op.add_column(
        'candidate_profiles',
        sa.Column('target_role', target_role, nullable=True),
    )
    # server_default only for the backfill of existing rows; the ORM supplies
    # the value on every insert thereafter, matching the codebase's
    # application-side-defaults convention (DATA_MODEL.md §0.4).
    op.add_column(
        'candidate_profiles',
        sa.Column('profile_strength', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'candidate_profiles',
        sa.Column('is_discoverable', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('candidate_profiles', 'profile_strength', server_default=None)
    op.alter_column('candidate_profiles', 'is_discoverable', server_default=None)

    op.create_index(op.f('ix_candidate_profiles_college'), 'candidate_profiles', ['college'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_degree'), 'candidate_profiles', ['degree'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_branch'), 'candidate_profiles', ['branch'], unique=False)
    op.create_index(
        op.f('ix_candidate_profiles_graduation_year'), 'candidate_profiles', ['graduation_year'], unique=False
    )
    op.create_index(op.f('ix_candidate_profiles_location'), 'candidate_profiles', ['location'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_target_role'), 'candidate_profiles', ['target_role'], unique=False)
    op.create_index(
        op.f('ix_candidate_profiles_is_discoverable'), 'candidate_profiles', ['is_discoverable'], unique=False
    )

    # --- Section 2: technical verification claims ---
    op.create_table(
        'github_accounts',
        sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
        sa.Column('github_username', sa.String(length=100), nullable=False),
        sa.Column('profile_url', sa.String(length=500), nullable=False),
        sa.Column('github_user_id', sa.BigInteger(), nullable=True),
        sa.Column('verification_status', verification_status, nullable=False),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('github_user_id'),
    )
    op.create_index(
        op.f('ix_github_accounts_candidate_profile_id'), 'github_accounts', ['candidate_profile_id'], unique=False
    )

    op.create_table(
        'coding_platform_accounts',
        sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
        sa.Column('platform', coding_platform, nullable=False),
        sa.Column('handle', sa.String(length=100), nullable=False),
        sa.Column('profile_url', sa.String(length=500), nullable=False),
        sa.Column('verification_status', verification_status, nullable=False),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('candidate_profile_id', 'platform', name='uq_coding_platform_per_candidate'),
    )
    op.create_index(
        op.f('ix_coding_platform_accounts_candidate_profile_id'),
        'coding_platform_accounts',
        ['candidate_profile_id'],
        unique=False,
    )

    # --- Section 3: projects (repo link or described) ---
    op.create_table(
        'projects',
        sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
        sa.Column('kind', project_kind, nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('repo_url', sa.String(length=500), nullable=True),
        sa.Column('technologies', postgresql.ARRAY(sa.String(length=60)), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('verification_status', verification_status, nullable=False),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_projects_candidate_profile_id'), 'projects', ['candidate_profile_id'], unique=False)

    # --- Section 4: certificates ---
    op.create_table(
        'certificates',
        sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('issuer', sa.String(length=200), nullable=False),
        sa.Column('issued_at', sa.Date(), nullable=True),
        sa.Column('credential_url', sa.String(length=500), nullable=True),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('verification_status', verification_status, nullable=False),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_certificates_candidate_profile_id'), 'certificates', ['candidate_profile_id'], unique=False
    )

    # --- Section 5: experience ---
    op.create_table(
        'experiences',
        sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
        sa.Column('company_name', sa.String(length=200), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('employment_type', employment_type, nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('technologies', postgresql.ARRAY(sa.String(length=60)), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_experiences_candidate_profile_id'), 'experiences', ['candidate_profile_id'], unique=False
    )


def downgrade() -> None:
    bind = op.get_bind()

    op.drop_index(op.f('ix_experiences_candidate_profile_id'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_certificates_candidate_profile_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_projects_candidate_profile_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_coding_platform_accounts_candidate_profile_id'), table_name='coding_platform_accounts')
    op.drop_table('coding_platform_accounts')
    op.drop_index(op.f('ix_github_accounts_candidate_profile_id'), table_name='github_accounts')
    op.drop_table('github_accounts')

    op.drop_index(op.f('ix_candidate_profiles_is_discoverable'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_target_role'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_location'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_graduation_year'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_branch'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_degree'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_college'), table_name='candidate_profiles')

    for column in (
        'is_discoverable',
        'profile_strength',
        'target_role',
        'location',
        'graduation_year',
        'branch',
        'degree',
        'college',
        'headline',
    ):
        op.drop_column('candidate_profiles', column)

    # Enum types are dropped only after every column referencing them is gone.
    employment_type.drop(bind, checkfirst=True)
    project_kind.drop(bind, checkfirst=True)
    coding_platform.drop(bind, checkfirst=True)
    target_role.drop(bind, checkfirst=True)
    branch_enum.drop(bind, checkfirst=True)
    degree_type.drop(bind, checkfirst=True)
    verification_status.drop(bind, checkfirst=True)
